service: serverless-nodejs-api
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  # deploymentBucket:
  #   name: serverless-nodejs-api-pro-serverlessdeploymentbuck-yjfrsugorh6j
  environment:
    DATABASE_URL: ${env:DATABASE_URL, "fallback value"}
    STAGE: ${env.STAGE, "prod"}
functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: '*'
custom:
  dotenv:
    exclude:
      -DATABASE_URL

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
